#! /bin/sh
#
# chkconfig: 345 99 01
# description: This service authenticates pf9 websocket connections against Keystone
#
### BEGIN INIT INFO
# Provides: pf9-authproxy
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: This service authenticates pf9 websocket connections against Keystone
### END INIT INFO

# read & export proxy information
. /etc/environment

prog="pf9-authproxy.js"
svcname="pf9-authproxy"

SERVER_BIN="/opt/pf9/authproxy/$prog"
KEYSTONE_FILE="/etc/keystone/keystone.conf"
SERVER_LOGFILE=/var/log/pf9-authproxy.log

# Source function library.
. /etc/init.d/functions


RETVAL=0
uid=`id | cut -d\( -f1 | cut -d= -f2`

start() {

	[ -f $SERVER_BIN ] || exit 5

	# Make sure the pf9-authproxy is not already running.
	if status $prog > /dev/null ; then
		exit 0
	fi

	# Only root can start the service
	[ $uid -ne 0 ] && exit 4

	[ -f $KEYSTONE_FILE ] || exit 5
        pattern="^[ \t]*admin_token[ \t]*=[ \t]*.*"
        adminkeyline=`grep "$pattern" $KEYSTONE_FILE`
        token=`expr match "$adminkeyline" 'admin_token = \(.*\)'`
        if [ "$token" == "" ]; then
            echo -n "Failed to extract keystone token"
            exit 1
        fi
        SERVER_OPTS="-t $token"

	echo -n $"Starting $svcname: "
        touch "$SERVER_LOGFILE"
        chown pf9 "$SERVER_LOGFILE"

	# Run process as pf9 user
        su -c "$SERVER_BIN $SERVER_OPTS >> $SERVER_LOGFILE 2>&1 &" pf9
	RETVAL=$?
	echo
	if [ $RETVAL -eq 0 ] ; then
		touch /var/lock/subsys/$svcname
		[ ! -f /var/run/pf9-authproxy.pid ] &&
			/sbin/pidof $prog > /var/run/pf9-authproxy.pid
	fi
	return $RETVAL
}


stop() {
	echo -n $"Stopping $svcname: "
	killproc $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && {
		rm -f /var/lock/subsys/$svcname
		rm -f /var/run/pf9-authproxy*
	}
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	RETVAL=$?
	;;
  stop)
	stop
	RETVAL=$?
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  restart | reload| force-reload)
	stop
	start
	RETVAL=$?
	;;
  condrestart | try-restart)
	if [ -f /var/lock/subsys/$svcname ]; then
		stop
		start -w
		RETVAL=$?
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
	RETVAL=2
	;;
esac

exit $RETVAL

